/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Bebas Neue', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        night: '#020209',
        void: '#07070f',
        cyan: { DEFAULT: '#00f5ff', dim: '#00b8c4' },
        violet: { DEFAULT: '#8b5cf6', bright: '#a78bfa' },
        magenta: { DEFAULT: '#f0abfc', bright: '#e879f9' },
        neon: '#39ff14',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 9s ease-in-out infinite',
        'float-slower': 'float 12s ease-in-out infinite',
        'spin-slow': 'spin 20s linear infinite',
        'spin-rev': 'spinrev 15s linear infinite',
        'shimmer': 'shimmer 3s linear infinite',
        'glow-pulse': 'glowpulse 2.5s ease-in-out infinite',
        'border-flow': 'borderflow 3s linear infinite',
        'scan': 'scan 3s linear infinite',
        'typewriter': 'typewriter 0.5s steps(1) forwards',
        'blink': 'blink 1s step-end infinite',
        'slide-right': 'slideright 0.8s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-up': 'slideup 0.7s cubic-bezier(0.16,1,0.3,1) forwards',
        'fade-in': 'fadein 0.6s ease forwards',
        'scale-in': 'scalein 0.5s cubic-bezier(0.16,1,0.3,1) forwards',
        'orbit': 'orbit 8s linear infinite',
        'orbit-rev': 'orbitrev 12s linear infinite',
        'marquee': 'marquee 20s linear infinite',
        'ping-slow': 'ping 3s cubic-bezier(0,0,0.2,1) infinite',
        'wave': 'wave 2.5s ease-in-out infinite',
      },
      keyframes: {
        float: { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-20px)' } },
        spinrev: { to: { transform: 'rotate(-360deg)' } },
        shimmer: { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        glowpulse: { '0%,100%': { opacity: '1', filter: 'blur(0px)' }, '50%': { opacity: '0.7', filter: 'blur(2px)' } },
        borderflow: { '0%': { backgroundPosition: '0% 50%' }, '100%': { backgroundPosition: '200% 50%' } },
        scan: { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(400%)' } },
        blink: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        slideright: { from: { opacity: '0', transform: 'translateX(-40px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideup: { from: { opacity: '0', transform: 'translateY(40px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadein: { from: { opacity: '0' }, to: { opacity: '1' } },
        scalein: { from: { opacity: '0', transform: 'scale(0.85)' }, to: { opacity: '1', transform: 'scale(1)' } },
        orbit: { from: { transform: 'rotate(0deg) translateX(80px) rotate(0deg)' }, to: { transform: 'rotate(360deg) translateX(80px) rotate(-360deg)' } },
        orbitrev: { from: { transform: 'rotate(0deg) translateX(120px) rotate(0deg)' }, to: { transform: 'rotate(-360deg) translateX(120px) rotate(360deg)' } },
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        wave: { '0%,100%': { transform: 'scaleY(0.4)' }, '50%': { transform: 'scaleY(1)' } },
      },
    }
  },
  plugins: [],
}
